### ISSUE TITLE
Apache config already contains git instructions

### ISSUE THREAD

**Issue by KaKi87** [crissyfield/repo-lookout#19]
Hi,

First of all, thank you for this project without which I would never have found out about exposed `.git` directories, as I've been living under the assumption that web servers protect hidden paths by default. :sweat_smile: 

Now, the wiki suggests adding lines to `httpd.conf`, but what I noticed before reading it is `/etc/apache2/conf-enabled/security.conf` already contains the following :

```
#
# Forbid access to version control directories
#
# If you use version control systems in your document root, you should
# probably deny access to their directories.
#
# Examples:
#
#RedirectMatch 404 /\.git
#RedirectMatch 404 /\.svn
```

So all I had to do is uncomment the line.

Additionally, when reading the email, I saw no indication that you were already providing a solution, which is why I looked for one myself, ensured that it works, then browsed the website to read about the story of this project, and finally stumbled on this.

Therefore, I would like to suggest adding a link to the wiki in the email.

On a side note :

> At this point, the repository does *not* contain the source code for the actual crawler software.

Will it ever ?

Thanks

**Comment by tja** [comment]
Thanks for your suggestions.

> So all I had to do is uncomment the line.

I understand that the suggestion in our wiki sounds too complicated for your setup. However, there are so many different setups out there that we decided to use the "brute force" method, which should (?!) work everywhere. But I fully agree that it's not ideal in all cases.

> Additionally, when reading the email, I saw no indication that you were already providing a solution, which is why I looked for one myself, ensured that it works, then browsed the website to read about the story of this project, and finally stumbled on this.

You're right. But that's already covered in #12 I believe.

> On a side note :
> 
> > At this point, the repository does not contain the source code for the actual crawler software.
> Will it ever ?

I really hope so!

As you can see from my super-slow response to this question, there's not a lot of effort going into this project at the moment. This is not for lack of interest, but due to other commitments that have a higher priority. I sincerely hope this will change in the second half of 2024, but I can't make any promises.

Open sourcing the project is the plan, but it's not the highest priority, I have to admit.

**Comment by KaKi87** [comment]
> there are so many different setups out there that we decided to use the "brute force" method

Don't all Apache installs must create the file I mentioned ?

**Comment by tja** [comment]
No, not that I'm aware of.

I checked in the official Apache source code repository and wasn't able to find a `security.conf` file, so I assume this is added by distribution maintainers. Googling a few minutes also showed that:

- [Alpine does not seem to install it](https://pkgs.alpinelinux.org/contents?file=&path=&name=apache2&branch=v3.20&repo=main&arch=ppc64le)
- [ArchLinux does not list the file](https://archlinux.org/packages/extra/x86_64/apache/)
- [FreeBSD doesn't list the file anywhere either](https://cgit.freebsd.org/ports/tree/www/apache24)

I know it's in (recent versions of) Debian and therefore Ubuntu, though.

**Comment by KaKi87** [comment]
How about suggesting creating *that* file *if it does not exist*, then ? Still simpler while covering all cases.

Though, most people do use Debian.

**Comment by tja** [comment]
Users often don't have access to this file, e.g. on shared web hosting.

Anyway, I do not think the current instructions need to be changed.
